#! /bin/sh
# dpdir

echo "Content-type: text/html"
echo
echo "<HTML><HEAD>"
echo "<TITLE>DPBOX directory list</TITLE>"
echo "</HEAD><BODY>"
echo '<BODY BGCOLOR="#ffffff">'

cat dptop.html

echo "<PRE>"
/installdir/dphttp "D $QUERY_STRING" | \
  /installdir/dpcodeconv | \
  /installdir/dpputlinks -dir
echo "</PRE>"

cat dpbottom.html

echo "</BODY></HTML>"
