/* Header for module box, generated by p2c */
#ifndef BOX_H
#define BOX_H

#include "pastrix.h"
#include "boxglobl.h"
#include "yapp.h"
#include "boxlocal.h"


extern void signalise_readlimit(short unr, boolean today,
				char *name, short von, short bis);
extern void add_readday(short unr, long count);
extern void begruessung(short unr);
extern void box_command_fract(short unr, char *command, boolean return_);
extern void show_sortcheck(short unr);
extern void show_fullcheck(short unr);
extern boolean erase_by_bid(boolean reread, char *sbid, char *eraseabsender);
extern void set_forward(short unr, short unr_msg, char *quelle, char *option,
			short nr, short bis, char *to_box, char *from_box,
			char *lastvias);
extern void check_remote_erase(long *seekp);
extern void add_remote_erase(char *absender, char *id1, char *rxfrom, char *id2);
extern void delete_brett_by_bid(char *brett, char *sfcall, char *bid,
				boolean release, boolean hidden);
extern boolean select_file(short unr, char *pfad, char *name, char *titel);
extern boolean analyse_boxcommand(short unr, char *eingabe, char *voll, boolean return_);
extern short search_by_bid(char *brett, char *bid, boolean hidden);
extern unsigned short read_brett(short unr, short outch, char *board,
  short von, short bis, short threshold, char *option, char *search, long sfoffset,
  indexstruct *header);
extern unsigned short read_for_bcast(char *rubrik, short nr, char *vname, indexstruct *header);
extern void list_brett(short unr, char *board, short von, short bis, short threshold,
		       char *option, char *search);
extern void run_sysbatch(char *name);
extern void disp_logptr(short unr, long checkct, boolean bidsearch,
			boxlogstruct *logptr, char *hs);
extern boolean check_access_ok(short unr, boolean userfiles, boolean nochb, boolean wantchb,
      	      	      	 boolean wants_distcheck, boolean wants_sendercheck, boxlogstruct *log);
extern void export_brett(short unr, char *brett, short s, short e, short threshold,
			 char *option1, char *search, char *fname);
extern boolean set_reply_flag(short unr, char *brett, short nr);
extern void add_eraseby(char *call, indexstruct *header);

#endif /*BOX_H*/

/* End. */
