/* Header for module box_tim, generated by p2c */
#ifndef BOX_TIM_H
#define BOX_TIM_H

#include "pastrix.h"
#include "boxglobl.h"

typedef void (*dpuaproc)(const short unr, const char *s);

extern void do_quit(short unr, boolean abort, boolean verbose);
extern void end_boxconnect(short unr);
extern void spoolendcheck(short unr);
extern void tell_command(char *call, char *bid, char *frage);
extern void stop_tell(short unr);
extern boolean tell_processing(char *tellfile);
extern void tell_check(void);
extern void timeout_check(short unr);
extern void show_mailbeacon(void);
extern void balise_check(void);
extern void add_zombie(pid_t pid, char *fname, short exitaction);
extern void kill_zombies(void);
extern void box_timing2(time_t tct);
extern void start_mailbeacon_manually(short unr);
extern void start_crawl(short unr, char *par);
extern void query_crawl(short unr, char *query);
extern void get_dpboxusage(short *u1, short *u5, short *u15);
extern void print_dpboxusage(short unr, dpuaproc outputproc);
extern void block_mailbox(boolean block, char *reason);

#endif /*BOX_TIM_H*/

