/* Header for module box_mem, generated by p2c */
#ifndef BOX_MEM_H
#define BOX_MEM_H


#include "pastrix.h"
#include "boxglobl.h"
#include "yapp.h"
#include "boxlocal.h"

extern long bidhash_active(void);
extern long hboxhash_active(void);
extern void disp_bidhash(short unr);
extern void disp_hboxhash(short unr);
extern void clear_bidhash(void);
extern void clear_hboxhash(void);
extern void load_initial_hbox(void);
extern void add_bptr(char *call, long bpos);
extern long load_hbox(short hboxhandle, char *call, hboxtyp *hbox);
extern long get_binstart(char *puffer, long size, char *fname);
extern void add_line_to_buff(char **buf1, long *size1, long inspos,
			     char *srline);
extern void write_msgid(long nr, char *ibuf);
extern boolean check_double(char *new_id);
extern long bull_mem(char *new_id, boolean delet);
extern void multiple_bullcheck(short ct, bidchecktype bidcheck,
			       bidarrtype bidarr);
extern void pack_entry(char **puffer, long *size, short *pmode);
extern long true_bin(char *zeile);

#endif /*BOX_MEM_H*/

