/* Header for module boxbcast, generated by p2c */
#ifndef BOXBCAST_H
#define BOXBCAST_H

#include "pastrix.h"

typedef void (*cbbproc)(const short unr, const char *s);

extern void load_boxbcastparms(char *name);
extern void free_boxbcastdesc(void);
extern void boxbcasttxtimer(void);
extern void show_bcastactivity(short unr, cbbproc outputproc);
extern void bccallback(long l);

#endif /*BOXBCAST_H*/

