/* Header for module boxfserv, generated by p2c */
#ifndef BOXFSERV_H
#define BOXFSERV_H

#include "pastrix.h"

extern void analyse_smode_command(short unr, char *eingabe, boolean return_);
extern void sig_7plus_incoming(boolean priv, char *name, char *original, char *board);
extern void smode_timer(void);

#endif /*BOXFSERV_H*/

