/* Header for module huffman, generated by p2c */

#ifndef HUFFMAN_H
#define HUFFMAN_H

#include "pastrix.h"

/* Hufman-Datenkompression dynamisch */

extern short enchuf(int gzip, int preserve_original, char *inf, char *outf, int crlfconv);
extern short dechuf(int gzip, int preserve_original, char *inf, char *outf, int crlfconv);

extern short enchufmem(int gzip, void *membase, long size, void **outbase,
		       long *outsize, char *outf, int crlfconv);
extern short dechufmem(int gzip, void *membase, long size, void **outbase,
		       long *outsize, char *outf, int crlfconv);

#endif /*HUFFMAN_H*/

