###############################################################################
#                                                                             #
# This is the Makefile of dpbox-6.00.00 for NetBSD                            #
#                                                                             #
# Version:     1.2.0                                                          #
# Date   :     15 May 2000                                                    #
# Author :     Berndt Josef Wulf, VK5ABN                                      #
#                                                                             #
###############################################################################

#
# uncomment for no shell access from within dpbox
#
NOSHELL		= -DNO_SHELL

INSTALL		= /usr/bin/install -c
INSTALL_PROGRAM	= ${INSTALL} -s 
INSTALL_DATA	= ${INSTALL} -m 444
INSTALL_CONF	= ${INSTALL} -m 440
MKDIR		= mkdir -p
LN		= ln -sf
CHMOD		= /bin/chmod
SED		= /usr/bin/sed
bindir		= $(prefix)/bin
sbindir		= $(prefix)/sbin
confdir		= $(prefix)/share/dpbox/conf
exampledir	= $(prefix)/share/examples/dpbox/conf
docdir		= $(prefix)/share/doc/dpbox
landir		= $(prefix)/share/dpbox/language
spooldir	= /var/spool/dpbox

cgidir		= $(prefix)/libexec/cgi-bin
httpdir		= $(prefix)/share/httpd/htdocs

DEFS		= $(SYSTEM) $(NOSHELL)
CC		= gcc
CPP		= $(CC) -E
CFLAGS		= -Wall -O2 -funsigned-char -fomit-frame-pointer -fno-strength-reduce -Wno-error=implicit-int -Wno-error=implicit-function-declaration -Wno-error=int-conversion
CRAWLERCFLAGS	= -Wall -O3 -funsigned-char -fomit-frame-pointer -fno-strength-reduce -Wno-error=implicit-int -Wno-error=implicit-function-declaration -Wno-error=int-conversion
LD		= $(CC)
LDFLAGS		= -s
LIBS		= -lm

HDRS		= filesys.h box.h box_file.h box_mem.h box_send.h box_sf.h \
                  box_sub.h box_sys.h boxdbox.h boxbcm.h box_tim.h box_init.h \
		  boxglobl.h boxlocal.h box_inou.h box_serv.h boxbcast.h \
		  boxfserv.h yapp.h crc.h huffman.h pastrix.h sort.h tools.h \
                  init.h dpbox.h ifacedef.h status.h linpack.h shell.h main.h \
		  box_garb.h box_logs.h box_wp.h box_rout.h box_scan.h md2md5.h

OBJS		= filesys.o box.o box_mem.o box_send.o box_sf.o box_sub.o \
                  box_sys.o boxdbox.o boxbcm.o box_tim.o boxglobl.o boxlocal.o \
		  box_inou.o box_serv.o boxbcast.o boxfserv.o yapp.o crc.o \
		  huffman.o pastrix.o sort.o box_file.o tools.o status.o \
		  shell.o init.o linpack.o main.o box_init.o box_garb.o \
		  box_logs.o box_wp.o box_rout.o box_scan.o md2md5.o

SRCS		= filesys.c box.c box_file.c box_mem.c box_send.c box_sf.c \
      	      	  box_sub.c box_sys.c boxdbox.c boxbcm.c box_tim.c boxglobl.c \
		  boxlocal.c box_inou.c box_serv.c boxbcast.c boxfserv.c \
		  yapp.c crc.c huffman.c pastrix.c sort.c tools.c status.c \
		  shell.c init.c linpack.c main.c box_init.c box_garb.c \
		  box_logs.c box_wp.c box_rout.c box_scan.c md2md5.c

OTHER_SRCS	= dpputlinks.c dpcodeconv.c dpgate.c crawler.c dpmybbs.c

all:	dpbox crawler cgi toolbox

tgz:
	@echo Creating dpboxsrc.tgz
	@tar -cvzf dpboxsrc.tgz $(SRCS) $(HDRS) $(OTHERS)

csource: $(SRCS)

.c.o:
	$(CC) $(CFLAGS) $(DEFS) -c $<

.c:
	$(CC) $(CFLAGS) $*.c -o $*

dpbox:	$(OBJS)
	$(LD) $(LDFLAGS) $(OBJS) $(LIBS) -o dpbox

crawler:	crawler.c
	$(CC) crawler.c $(CRAWLERCFLAGS) -o crawler

toolbox:  dpmybbs

cgi:	dpputlinks dpcodeconv dpgate

install: all
	$(MKDIR) $(sbindir)
	$(INSTALL_PROGRAM) dpbox $(sbindir)

	$(MKDIR) $(bindir)
	$(INSTALL_PROGRAM) -m 4511 dpgate $(bindir)
	$(INSTALL_PROGRAM) dpputlinks $(bindir)
	$(INSTALL_PROGRAM) dpcodeconv $(bindir)
	$(INSTALL_PROGRAM) dpmybbs $(bindir)
	$(SED) "s,/installdir,$(bindir)," < ../cgi/dpboxcgi/dphttp > $(bindir)/dphttp
	$(CHMOD) 555 $(bindir)/dphttp

	$(MKDIR) $(docdir)
	$(INSTALL_DATA) ../document/* $(docdir)

	$(MKDIR) $(landir)
	$(INSTALL_DATA) ../language/* $(landir)
	$(LN) DL.ALL $(landir)/BS.ALL
	$(LN) DL.ALL $(landir)/DLX.ALL
	$(LN) DL.ALL $(landir)/EY.ALL
	$(LN) DL.ALL $(landir)/HB.ALL
	$(LN) DL.ALL $(landir)/OE1.ALL
	$(LN) HELP.DL $(landir)/HELP.BS
	$(LN) HELP.DL $(landir)/HELP.DLX
	$(LN) HELP.DL $(landir)/HELP.EY
	$(LN) HELP.DL $(landir)/HELP.HB
	$(LN) HELP.DL $(landir)/HELP.OE1
	$(LN) HELP_SYS.DL $(landir)/HELP_SYS.BS
	$(LN) HELP_SYS.DL $(landir)/HELP_SYS.DLX
	$(LN) HELP_SYS.DL $(landir)/HELP_SYS.EY
	$(LN) HELP_SYS.DL $(landir)/HELP_SYS.HB
	$(LN) HELP_SYS.DL $(landir)/HELP_SYS.OE1

	$(MKDIR) $(prefix)/libexec/dpbox
	$(INSTALL) -m 555 ../run/* $(prefix)/libexec/dpbox
	$(INSTALL_PROGRAM) crawler $(prefix)/libexec/dpbox

	$(MKDIR) $(exampledir)
	$(INSTALL_CONF) ../dpbox.ini $(exampledir)/dpbox.ini
	$(MKDIR) $(exampledir)/crawler
	$(INSTALL_DATA) ../crawler/stopwords $(exampledir)/crawler
	$(MKDIR) $(exampledir)/system
	$(INSTALL_CONF) ../system/* $(exampledir)/system
	$(MKDIR) $(exampledir)/sf
	$(INSTALL_CONF) ../sf/* $(exampledir)/sf

	$(MKDIR) $(cgidir)
	echo "installing cgi-scripts";
	@for i in `ls -1 ../cgi/cgi`; \
	do \
	  $(SED) "s,/installdir,$(bindir)," < ../cgi/cgi/$$i > $(cgidir)/$$i; \
	  $(CHMOD) 555 $(cgidir)/$$i; \
	done; \
	$(INSTALL_DATA) ../cgi/dpboxcgi/*.html $(cgidir);

	$(MKDIR) $(httpdir)
	echo "installing html pages";
	$(MKDIR) $(httpdir)/dpbox/pic;
	$(INSTALL_DATA) ../cgi/dpbox/*.html $(httpdir)/dpbox;
	$(INSTALL_DATA) ../cgi/dpbox/pic/* $(httpdir)/dpbox/pic;

	@echo
	@echo "***********************************************************"
	@echo "*                                                         *"
	@echo "* The installation of dpbox is now completed.             *"
	@echo "*                                                         *"
	@echo "* Please read the documentation provided with this        *"
	@echo "* package carefully and edit all configuration files      *"
	@echo "* to reflect your system setup!                           *"
	@echo "*                                                         *"
	@echo "* The documentation can be found in                       *"
	@echo "*             $(docdir)                    *"
	@echo "*                                                         *"
	@echo "* The configuration files are located in                  *"
	@echo "*             $(confdir)                   *"
	@echo "*                                                         *"
	@echo "***********************************************************"
	@echo

clean:
	$(RM)  *.o *~ .*~ *.orig *.bak *.s *.core  
	$(RM)  fdpbox crawler dpgate dpputlinks dpcodeconv .depend tags

depend:	dep

dep:
	$(CPP) -M $(DEFS) $(SRCS) $(OTHER_SRCS) > .depend
#	@ctags $(SRCS) $(HDRS) $(OTHER_SRCS)

#
# include a dependency file if one exists
#
ifeq (.depend,$(wildcard .depend))
include .depend
endif
