/* Header for module sort, generated by p2c */
#ifndef SORT_H
#define SORT_H

#include "pastrix.h"

extern void gnusort(char *name, char *options1, char *options2);
extern void sort_file(char *name, boolean single);
extern void sort_mem(char *start, long *size, boolean single);

#endif /*SORT_H*/

