/* Header for module status, generated by p2c */
#ifndef STATUS_H
#define STATUS_H

#include "pastrix.h"

extern void free_statp(char **p);
extern long get_sysruntime(void);
extern void get_status(boolean sysop, char **p, long *sz);
extern void get_cpuinf(char *cpu, char *mips);
extern void get_sysload(char *s);
extern void get_lastsysload(char *s);
extern void get_sysversion(char *s);
extern void get_linpack(char *s);

#endif

