/* Header for module yapp, generated by p2c */
#ifndef YAPP_H
#define YAPP_H

#include "pastrix.h"

typedef void (*yappchouttype)(const short unr, const char b);
typedef void (*yapplineouttype)(const short unr, const char *s);
typedef void (*yappbuffouttype)(short unr, char *base, long size);

typedef struct yapptype {
  short			state, filefd, yappc;
  long			total, filelength;
  time_t		touch;
  boolean		delete_, write_;
  long			maxfill, seekpos;
  short			unr;
  yappchouttype		chout;
  yapplineouttype	lineout;
  yappbuffouttype	buffout;
  yapplineouttype	statout;

  long			outlen, outbufptr, buflen;
  char			outbuffer[512];
  char			buffer[1024];
  unsigned short	fdate, ftime;
  char			fname[256];
  char			yappdir[256];
} yapptype;

extern boolean yapp_upload(boolean init, boolean abort, yapptype *yapp,
			   char *buffp, long blen);
extern boolean yapp_download(boolean init, boolean abort, yapptype *yapp,
			     char *buffp, long blen);


#endif /*YAPP_H*/

/* End. */

